Do a test extraction before starting a Thrift server because "readability" sometimes fails rather late with a cryptic "AttributeError: 'module' object has no attribute 'Document'", so we want to catch this before extracting anything of importance